[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200

# 정적 파일
[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200

[[redirects]]
from = "/apps/*"
to = "/apps/:splat"
status = 200

# 11quiz
[[redirects]]
from = "/11quiz"
to = "/apps/11quiz/index.html"
status = 200

[[redirects]]
from = "/11quiz/*"
to = "/apps/11quiz/:splat"
status = 200

# sleeptime-calc
[[redirects]]
from = "/sleeptime-calc"
to = "/apps/sleeptime-calc/index.html"
status = 200

[[redirects]]
from = "/sleeptime-calc/*"
to = "/apps/sleeptime-calc/:splat"
status = 200
