# 정적 파일
[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200

[[redirects]]
from = "/apps/*"
to = "/apps/:splat"
status = 200

# 11quiz
[[redirects]]
from = "/11quiz/*"
to = "/apps/11quiz/:splat"
status = 200

# 루트만 main
[[redirects]]
from = "/"
to = "/apps/main/index.html"
status = 200